c=int(input("enter the value of first number"))
d=int(input("enter the value of second number"))
e=int(input("enter the value of third number"))
print("Largest value is:",max(c,d,e))
print("smallest value is :",min(c,d,e))
